Replace tabs with spaces, fix browser parse loop

diff --git a/browser b/browser
--- a/browser
+++ b/browser
@@ -13,19 +13,18 @@ Example:
 EOF
 }
 
-while (( $# > 0 ))
+for i in "$@"
 do
-	case "$1" in
-		-h|--help)
-			printHelp
-			exit
-			;;
-		-*)
-			echo "Invalid option: $1"
-			exit 1
+    case "$i" in
+        -h|--help)
+            printHelp
+            exit
             ;;
-	esac
-	shift
+        -*)
+            echo "Invalid option: $i"
+            exit 1
+            ;;
+    esac
 done
 
 # Check if stdin is a terminal.
diff --git a/jwt-decode b/jwt-decode
--- a/jwt-decode
+++ b/jwt-decode
@@ -17,16 +17,16 @@ EOF
 
 for i in "$@"
 do
-	case "$i" in
-		-h|--help)
-			printHelp
-			exit
-			;;
-		-*)
-			echo "Invalid option: $i"
-			exit 1
+    case "$i" in
+        -h|--help)
+            printHelp
+            exit
             ;;
-	esac
+        -*)
+            echo "Invalid option: $i"
+            exit 1
+            ;;
+    esac
 done
 
 function printJwt {
diff --git a/vpn b/vpn
--- a/vpn
+++ b/vpn
@@ -21,16 +21,16 @@ EOF
 
 for i in "$@"
 do
-	case "$i" in
-		-h|--help)
-			printHelp
-			exit
-			;;
-		-*)
-			echo "Invalid option: $i"
-			exit 1
+    case "$i" in
+        -h|--help)
+            printHelp
+            exit
             ;;
-	esac
+        -*)
+            echo "Invalid option: $i"
+            exit 1
+            ;;
+    esac
 done
 
 # If no argument is given, list the VPN configs.
