Add gitignore, help flags for each script, update readme

diff --git a/browser b/browser
--- a/browser
+++ b/browser
@@ -1,17 +1,41 @@
 #!/usr/bin/env bash
-set -eu
+set -euo pipefail
+
+printHelp()
+{
+    cat <<EOF
+Pipe HTML to your browser.
+
+Usage: [...] | browser
+
+Example:
+    echo '<h1>Hello world</h1>' | browser
+EOF
+}
+
+while (( $# > 0 ))
+do
+	case "$1" in
+		-h|--help)
+			printHelp
+			exit
+			;;
+		-*)
+			echo "Invalid option: $1"
+			exit 1
+            ;;
+	esac
+	shift
+done
 
 # Check if stdin is a terminal.
 if [ -t 0 ]
 then
-    cat <<EOF
-Usage: browser
-       pipe html to a browser
-
-$ echo '<h1>Hello world</h1>' | browser
-EOF
+    printHelp
 else
+    # Write the command output to a random temporary file.
     f="/tmp/browser.$RANDOM.html"
     cat /dev/stdin > "$f"
+    # Open the file in the browser.
     "$BROWSER" "$f"
 fi
diff --git a/composer-link b/composer-link
--- a/composer-link
+++ b/composer-link
@@ -1,10 +1,34 @@
 #!/usr/bin/env bash
-set -eu
+set -euo pipefail
 
-# Usage: composer-link ../local-package package/name
-# Where:
-#   ../local-package is the path to the package code on the filesystem
-#   package/name is the composer name of that package
+printHelp()
+{
+    cat <<EOF
+Link a Composer dependency to a local directory.
+
+Usage: composer-link <path> <package> [repository]
+
+Example:
+    composer-link ../local-package package/name
+Where:
+    "../local-package" is the path to the package code on the filesystem;
+    "package/name" is the composer name of that package.
+EOF
+}
+
+for i in "$@"
+do
+	case "$i" in
+		-h|--help)
+			printHelp
+			exit
+			;;
+		-*)
+			echo "Invalid option: $i"
+			exit 1
+            ;;
+	esac
+done
 
 repositoryName=${3:-local}
 composer config repositories.$repositoryName '{"type": "path", "url": "'$1'", "options": {"symlink": true}}' --file composer.json
diff --git a/jwt-decode b/jwt-decode
--- a/jwt-decode
+++ b/jwt-decode
@@ -1,6 +1,34 @@
 #!/usr/bin/env bash
 set -euo pipefail
 
+printHelp()
+{
+    cat <<EOF
+Decode and display a JSON Web Token.
+
+Usage: jwt-decode [token]
+
+Example:
+    jwt-decode eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMiLCJpYXQiOjE1MTYyMzkwMjJ9.qSxzXSZwDRsi3oqx3fBZ2ah8gOIsQZE0Lgkl0kjJ3Ko
+Or:
+    echo eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMiLCJpYXQiOjE1MTYyMzkwMjJ9.qSxzXSZwDRsi3oqx3fBZ2ah8gOIsQZE0Lgkl0kjJ3Ko | jwt-decode
+EOF
+}
+
+for i in "$@"
+do
+	case "$i" in
+		-h|--help)
+			printHelp
+			exit
+			;;
+		-*)
+			echo "Invalid option: $i"
+			exit 1
+            ;;
+	esac
+done
+
 function printJwt {
     # Split the line on '.'.
     IFS='.' read -a PARTS <<< "$1"
diff --git a/repo b/repo
--- a/repo
+++ b/repo
@@ -1,5 +1,28 @@
 #!/usr/bin/env bash
-set -eu
+set -euo pipefail
+
+printHelp()
+{
+    cat <<EOF
+Open the remote repository in your browser.
+
+Usage: repo
+EOF
+}
+
+for i in "$@"
+do
+	case "$i" in
+		-h|--help)
+			printHelp
+			exit
+			;;
+		-*)
+			echo "Invalid option: $i"
+			exit 1
+            ;;
+	esac
+done
 
 # Example remote:
 # origin  git@gitlab.com:path/to/repo.git (fetch)
diff --git a/vpn b/vpn
--- a/vpn
+++ b/vpn
@@ -3,10 +3,40 @@ set -euo pipefail
 
 vpnDir="$HOME/Documents/vpn"
 
+
+printHelp()
+{
+    cat <<EOF
+Connect to a VPN profile.
+
+Usage: vpn [profile]
+
+Example:
+    vpn office
+Where:
+    an "office.ovpn" file exists in the VPN profile directory ($vpnDir);
+    an "office_pass.txt" file exists in the VPN profile directory (if required).
+EOF
+}
+
+for i in "$@"
+do
+	case "$i" in
+		-h|--help)
+			printHelp
+			exit
+			;;
+		-*)
+			echo "Invalid option: $i"
+			exit 1
+            ;;
+	esac
+done
+
 # If no argument is given, list the VPN configs.
 if [ -z ${1+x} ]
 then
-    echo 'Available VPN files:'
+    echo 'Available VPN profiles:'
 
     for file in "$vpnDir/"*".ovpn"
     do
@@ -26,13 +56,13 @@ passFile="$vpnDir/$1_pass.txt"
 # Check if a name is given.
 if [ ! -f "$ovpnFile" ]
 then
-    echo "No VPN file found for '$1'"
+    echo "No VPN profile found for '$1'"
     exit 1
 fi
 
 vpnCommand="sudo openvpn --config $ovpnFile"
 
-# Check if a pass file exists, if so, add a flag to the command.
+# Check if a pass file exists. If so, add a flag to the command.
 if [ -f "$passFile" ]
 then
     vpnCommand="$vpnCommand --auth-user-pass $passFile"
